#!/usr/bin/env python3
"""Render the unlisted ITP journal with Python's standard library."""
import argparse
from datetime import date
from html import escape
import json
from pathlib import Path
import re
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
MARKER = '<!-- Generated by _itp/build.py. Edit _itp/content.json. -->'


def e(value):
    return escape(str(value), quote=True)


def slug(value):
    if not isinstance(value, str) or not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', value):
        raise ValueError(f'Invalid slug: {value!r}')
    return value


def url(value):
    parsed = urlsplit(value)
    if parsed.scheme == 'https' and parsed.netloc:
        return e(value)
    if value.startswith('/') and not value.startswith('//') and '\\' not in value:
        return e(value)
    raise ValueError('Use an https URL or a site-relative path beginning with /.')


def inline(value):
    """A string, or an ordered array of text, links, emphasis and strong text."""
    if isinstance(value, str):
        return e(value)
    parts = []
    for part in value:
        if isinstance(part, str):
            parts.append(e(part))
        elif 'href' in part:
            parts.append(f'<a href="{url(part["href"])}">{e(part["text"])}</a>')
        elif part.get('type') in ('em', 'strong', 'code'):
            tag = part['type']
            parts.append(f'<{tag}>{e(part["text"])}</{tag}>')
        else:
            raise ValueError(f'Unknown inline content: {part!r}')
    return ''.join(parts)


def block(item):
    kind = item['type']
    if kind == 'paragraph':
        return f'<p>{inline(item["text"])}</p>'
    if kind == 'heading':
        level = item.get('level', 2)
        if level not in (2, 3):
            raise ValueError('Post headings must be level 2 or 3.')
        return f'<h{level}>{e(item["text"])}</h{level}>'
    if kind in ('image', 'video', 'audio'):
        src = url(item['src'])
        if kind == 'image':
            media = f'<img src="{src}" alt="{e(item["alt"])}" loading="lazy" decoding="async">'
        else:
            media = f'<{kind} src="{src}" controls preload="metadata" aria-label="{e(item["label"])}"><a href="{src}">Open {kind}</a></{kind}>'
        caption = f'<figcaption>{inline(item["caption"])}</figcaption>' if item.get('caption') else ''
        return f'<figure>{media}{caption}</figure>'
    if kind == 'quote':
        cite = f'<cite>{e(item["attribution"])}</cite>' if item.get('attribution') else ''
        return f'<blockquote><p>{inline(item["text"])}</p>{cite}</blockquote>'
    if kind == 'list':
        tag = 'ol' if item.get('ordered') else 'ul'
        return f'<{tag}>' + ''.join(f'<li>{inline(x)}</li>' for x in item['items']) + f'</{tag}>'
    if kind == 'code':
        return f'<pre><code>{e(item["text"])}</code></pre>'
    if kind == 'divider':
        return '<hr>'
    raise ValueError(f'Unknown block type: {kind}')


def page(title, path, content, back_href='/', back_label='homepage', post=False, compact=False):
    media_styles = '\n  <link rel="stylesheet" href="/itp/post-media.css">' if post or compact else ''
    main_class = ' class="content-wrapper itp-article"' if post else ''
    return f'''<!DOCTYPE html>
{MARKER}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow, noarchive">
  <meta name="referrer" content="no-referrer">
  <title>{e(title)} - Avinash Krishna</title>
  <link rel="canonical" href="https://www.avikrishna.com{path}">
  <link rel="stylesheet" href="/styles/style.css">{media_styles}
</head>
<body>
  <main{main_class}>
    {content}
  </main>
  <div class="back-button">
    <a href="{e(back_href)}">← Back to {e(back_label)}</a>
  </div>
</body>
</html>
'''


def post_path(post):
    return f'/itp/{post["course"]}/{post["slug"]}/'


def date_label(value):
    d = date.fromisoformat(value)
    return f'{d:%B} {d.day}, {d.year}'


def render(data):
    courses = {slug(c['slug']): c for c in data['courses']}
    if len(courses) != len(data['courses']):
        raise ValueError('Duplicate course slug.')
    posts = []
    seen = set()
    for p in data['posts']:
        slug(p['slug'])
        if p['course'] not in courses:
            raise ValueError(f'Unknown course: {p["course"]}')
        path = post_path(p)
        if path in seen:
            raise ValueError(f'Duplicate post URL: {path}')
        seen.add(path)
        if p.get('published') is True:
            date.fromisoformat(p['date'])
            if not p['title'].strip() or not p['blocks']:
                raise ValueError('Published posts need a title and content.')
            posts.append(p)
    posts.sort(key=lambda p: p['date'], reverse=True)
    pages = {}
    rows = '\n      '.join(f'<li>- <a href="/itp/{c["slug"]}/">{e(c["title"])}</a></li>' for c in courses.values())
    content = f'<h1><b>ITP</b></h1>\n    <ul>\n      {rows}\n    </ul>'
    pages['itp/index.html'] = page('ITP', '/itp/', content)
    for c in courses.values():
        entries = ''
        for p in posts:
            if p['course'] != c['slug']:
                continue
            summary = f'<p>{e(p["summary"])}</p>' if p.get('summary') else ''
            entries += f'<li>- <a href="{post_path(p)}">{e(p["title"])}</a><small class="itp-post-date"><time datetime="{e(p["date"])}">{date_label(p["date"])}</time></small>{summary}</li>\n'
        entries = f'<ul>\n{entries}</ul>' if entries else '<p>No posts yet.</p>'
        content = f'<h1><b>{e(c["title"])}</b></h1>\n    {entries}'
        pages[f'itp/{c["slug"]}/index.html'] = page(c['title'], f'/itp/{c["slug"]}/', content, '/itp/', 'ITP', compact=True)
    for p in posts:
        c = courses[p['course']]
        summary = f'<p>{e(p["summary"])}</p>' if p.get('summary') else ''
        body = '\n'.join(block(b) for b in p['blocks'])
        content = f'<article><h1><b>{e(p["title"])}</b></h1><div class="robot-intro itp-post"><p><time datetime="{e(p["date"])}">{date_label(p["date"])}</time></p>{summary}\n{body}</div></article>'
        pages[post_path(p).lstrip('/') + 'index.html'] = page(p['title'], post_path(p), content, f'/itp/{c["slug"]}/', c['title'], post=True)
    return pages


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify generated pages without writing.')
    args = parser.parse_args()
    pages = render(json.loads((ROOT / '_itp/content.json').read_text()))
    stale = [p for p in (ROOT / 'itp').rglob('index.html') if MARKER in p.read_text() and str(p.relative_to(ROOT)) not in pages]
    if args.check:
        errors = [p for p, html in pages.items() if not (ROOT / p).exists() or (ROOT / p).read_text() != html]
        if errors or stale:
            raise SystemExit(f'Rebuild the journal: {errors + [str(p) for p in stale]}')
    else:
        for path, html in pages.items():
            target = ROOT / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(html)
        for path in stale:
            path.unlink()
    print(f'{"Checked" if args.check else "Built"} {len(pages)} ITP pages.')


if __name__ == '__main__':
    main()
